- name: Copy dump_snapshot.sh/restore_snapshot.sh
  copy:
    src: "blockchain/{{item}}"
    dest: /workspace
    mode: 0700
  with_items:
  - dump_snapshot.sh
  - restore_snapshot.sh

- name: Directory 'snapshots' created
  file:
    path=/workspace/snapshots
    state=directory

- name: Directory 'snapshots/ansible' created
  file:
    path=/workspace/snapshots
    state=directory

- name: Blockchain snapshot downloaded
  get_url:
    url: "{{ snapshot_url }}"
    checksum: "sha256:{{ snapshot_sha256 }}"
    dest: /workspace/snapshots/ansible/{{ snapshot_download_filename }}
    # use tmp_dest to work around https://github.com/ansible/ansible/issues/18894
    tmp_dest: /tmp

- name: Restore from snapshot
  shell: "./restore_snapshot.sh {{ blockchain_database_name }} /workspace/snapshots/ansible/{{ snapshot_download_filename }} && touch /workspace/snapshots/ansible/restored.yes"
  args:
    chdir: /workspace
    creates: /workspace/snapshots/ansible/restored.yes

- name: Create cron_dump_snapshot.sh
  template:
    src: blockchain/cron_dump_snapshot.sh
    dest: /workspace
    mode: 0700

- name: Setup cron job for snapshots
  cron:
    name: snapshots
    # Run every 12 hours
    month: "*"
    day: "*"
    hour: "*/12"
    minute: "0"
    user: "{{ ansible_ssh_user }}"
    job: /workspace/cron_dump_snapshot.sh
