- name: Copy dump_snapshot.sh/restore_snapshot.sh
  copy:
    src: "blockchain/{{item}}"
    dest: /workspace
    mode: 0700
  with_items:
  - dump_snapshot.sh
  - restore_snapshot.sh

- name: Directory 'snapshots' created
  file:
    path=/workspace/snapshots
    state=directory

- name: Blockchain snapshot downloaded
  get_url:
    url: "{{ snapshot_url }}"
    checksum: "sha256:{{ snapshot_sha256 }}"
    dest: /workspace/snapshots/{{ snapshot_download_filename }}
    # use tmp_dest to work around https://github.com/ansible/ansible/issues/18894
    tmp_dest: /tmp

- name: Restore from snapshot
  shell: "./restore_snapshot.sh {{ blockchain_database_name }} /workspace/snapshots/{{ snapshot_download_filename }} && touch /workspace/snapshots/restored.yes"
  args:
    chdir: /workspace
    creates: /workspace/snapshots/restored.yes

- name: Create cron_dump_snapshot.sh
  template:
    src: blockchain/cron_dump_snapshot.sh
    dest: /workspace
    mode: 0700
