- name: Packages installed
  become: true
  apt:
    name:
    - curl
    - jq
    state: present

- name: Copy start_forging.sh
  template:
    src: "forging/{{item}}"
    dest: /workspace
    mode: 0700
  with_items:
  - start_forging.sh

- name: Create directory ~/.lisk_node
  file:
    path: ~/.lisk_node
    state: directory
    mode: 0700

- name: Create empty file ~/.lisk_node/pubkey, ~/.lisk_node/secret
  file:
    path: ~/.lisk_node/{{ item }}
    state: touch
    mode: 0600
  with_items:
  - pubkey
  - secret
