- name: Add an apt signing key, will not download if present
  become: true
  apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodesource.com repo
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x bionic main
    state: present

- name: Packages installed
  become: true
  apt:
    name:
    - nodejs
    - python-dev # for node-gyp, see https://github.com/lovell/sharp/issues/1087
    state: present
