- name: Database packages installed
  become: true
  apt:
    name:
    - postgresql
    - python3-psycopg2 # for the postgresql_user Ansible module
    state: present

- name: Create database and database user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ ansible_ssh_user }}"
    encrypted: true
    password: password
    role_attr_flags: CREATEDB
